In [ ]:
print ('hi')

hi


Импорт библиотеки NumPy

In [1]:
import numpy as np


массив из 10 нулей

In [2]:
array=np.zeros(10)
print('10 null')
print(array)

10 null
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


массив из 10 единиц

In [3]:
array=np.ones(10)
print('10 units')
print(array)

10 units
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


массив из 10 пятерок

In [4]:
array=np.ones(10)*5
print('10 fives')
print(array)

10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


массив из целых чисел от 10 до 50

In [5]:
array=np.arange(10,51)
print('from 10 to 50')
print(array)

from 10 to 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


массив из четных чисел от 10 до 50

In [6]:
array=np.arange(10,51,2)
print('from 10 to 50')
print(array)

from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


матрица 3х3 с числами от 0 до 8

In [7]:
mat= np.arange(0,9).reshape (3,3)
print (mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


единичная матрица 3x3

In [8]:
mat = np.eye(3)
print (mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Генерация случайного числа от 0 до 1

In [9]:
rand = np.random.rand(1)
print("from 0 to 1")
print(rand)

from 0 to 1
[0.01659607]


Генерация массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [10]:
rand = np.random.rand(25)
print("25 random numbers")
print(rand)

25 random numbers
[0.58383861 0.96015507 0.94837336 0.35750823 0.16807421 0.11295067
 0.00283208 0.75729861 0.13533002 0.51383078 0.74217642 0.07379693
 0.42513009 0.94171187 0.09234858 0.96781241 0.33413569 0.27282721
 0.97831479 0.18929627 0.1172818  0.33973866 0.05291587 0.71125025
 0.62355934]


Создать матрицу используя функции библиотеки NumPy

In [11]:
mat= np.arange (0.01, 1.01, 0.01).reshape (10,10)
print (mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Cтартовая матрица

In [12]:
mat = np.arange(1,26).reshape(5,5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Код который вернет матрицу из стартовой

In [13]:
print ('array = ', mat [2:,1:])

array =  [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Код обращения к элементу который вернет значение  20 

In [14]:
twenty = mat [mat==20]
print(twenty)

[20]


Вывод 2,7,12

In [15]:
print ('array=', mat [0:3,1].reshape(3,1))

array= [[ 2]
 [ 7]
 [12]]


Вывод 21,22,23,24,25

In [16]:
print ('array=', mat [4:])

array= [[21 22 23 24 25]]


Вывод 3 и 4 строки

In [17]:
print ('array=', mat [3:])

array= [[16 17 18 19 20]
 [21 22 23 24 25]]


Сумма всех значений в стартовой матрице mat

In [18]:
print(mat.sum())

325


Cтандартное отклонение в стартовой матрице mat

In [19]:
print(mat.std())

7.211102550927978


Сумма значений в колонках в стартовой матрице mat

In [20]:
print(mat.sum(axis=0))

[55 60 65 70 75]
